version: '3.8'

volumes:
  orderer1.hypctt.com:

networks:
  hypcttnetwork:
services:
  orderer1.hypctt.com:
    container_name: orderer1.hypctt.com
    image: hyperledger/fabric-orderer:2.5.9
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none 
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:7053
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/admin/tls/ca.crt]
      # - ORDERER_OPERATIONS_LISTENADDRESS=orderer1.hypctt.com:9443

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes: 
      - ../../crypto-config/ordererOrganizations/hypctt.com/orderers/orderer1.hypctt.com/msp:/var/hyperledger/orderer/msp
      - ../../crypto-config/ordererOrganizations/hypctt.com/orderers/orderer1.hypctt.com/tls/:/var/hyperledger/orderer/tls
      - ../../crypto-config/ordererOrganizations/hypctt.com/users/Admin@hypctt.com/:/var/hyperledger/orderer/admin
      - orderer1.hypctt.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7053:7053
      # - 9443:9443
    networks:
      - hypcttnetwork 